version: '2'
services:
  
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    links:
      - auth
      - redis
    depends_on:
      - mongo
    tty: true

  auth:
    image: jincort/backend-auth:production
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
      THROTTLER_WHITE_LIST: "*"
      TENANT_WHITE_LIST: "*"
    ports:
      - "3000"
      - "4000"
    links:
      - redis

  redis:
    image: jincort/backend-redis:production
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
        - ./storage/mongodb:/data/db
    ports:
      - 27017:27017
      - 28017:28017