version: '2'
services:
  
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - mongo
    tty: true

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./:/var/www/app
    command: "sh -c 'yarn && yarn run work'"
    links:
        - redis

  redis:
    image: jincort/backend-redis:production
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
        - ./storage/mongodb:/data/db
    ports:
      - 27017:27017
      - 28017:28017